-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dft is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    real_sample_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    real_sample_TVALID : IN STD_LOGIC;
    real_sample_TREADY : OUT STD_LOGIC;
    real_sample_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    real_sample_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    real_sample_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    imag_sample_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_sample_TVALID : IN STD_LOGIC;
    imag_sample_TREADY : OUT STD_LOGIC;
    imag_sample_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    imag_sample_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    imag_sample_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    real_op_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_op_TVALID : OUT STD_LOGIC;
    real_op_TREADY : IN STD_LOGIC;
    real_op_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_op_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    real_op_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    imag_op_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_op_TVALID : OUT STD_LOGIC;
    imag_op_TREADY : IN STD_LOGIC;
    imag_op_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    imag_op_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    imag_op_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of dft is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dft_dft,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=6293532,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=1269,HLS_SYN_LUT=1861,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal real_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal real_sample_data_ce0 : STD_LOGIC;
    signal real_sample_data_we0 : STD_LOGIC;
    signal real_sample_data_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_sample_data_ce0 : STD_LOGIC;
    signal imag_sample_data_we0 : STD_LOGIC;
    signal imag_sample_data_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal real_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal real_op_data_ce0 : STD_LOGIC;
    signal real_op_data_we0 : STD_LOGIC;
    signal real_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal real_op_data_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal imag_op_data_ce0 : STD_LOGIC;
    signal imag_op_data_we0 : STD_LOGIC;
    signal imag_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_op_data_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_idle : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_ready : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_TREADY : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_TREADY : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_idle : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_ready : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_we0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_idle : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_ready : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TREADY : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TREADY : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_ce0 : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID : STD_LOGIC;
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal real_op_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal real_op_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal real_op_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal real_op_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal imag_op_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_op_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal imag_op_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal imag_op_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal regslice_both_real_op_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_imag_op_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state8 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_real_sample_V_data_V_U_apdone_blk : STD_LOGIC;
    signal real_sample_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal real_sample_TVALID_int_regslice : STD_LOGIC;
    signal real_sample_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_real_sample_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_sample_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal real_sample_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_sample_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_sample_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_sample_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal real_sample_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_sample_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_sample_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_real_sample_V_last_V_U_apdone_blk : STD_LOGIC;
    signal real_sample_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_real_sample_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_sample_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_sample_V_data_V_U_apdone_blk : STD_LOGIC;
    signal imag_sample_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_sample_TVALID_int_regslice : STD_LOGIC;
    signal imag_sample_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_imag_sample_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_sample_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal imag_sample_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_sample_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_sample_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_sample_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal imag_sample_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_sample_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_sample_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_imag_sample_V_last_V_U_apdone_blk : STD_LOGIC;
    signal imag_sample_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_imag_sample_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_sample_V_last_V_U_ack_in : STD_LOGIC;
    signal real_op_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal real_op_TVALID_int_regslice : STD_LOGIC;
    signal real_op_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_real_op_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_op_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal real_op_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_op_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_real_op_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_op_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal real_op_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_real_op_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_real_op_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_real_op_V_last_V_U_apdone_blk : STD_LOGIC;
    signal real_op_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_real_op_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_real_op_V_last_V_U_vld_out : STD_LOGIC;
    signal imag_op_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_op_TVALID_int_regslice : STD_LOGIC;
    signal imag_op_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_imag_op_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_op_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal imag_op_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_op_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_imag_op_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_op_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal imag_op_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_imag_op_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_imag_op_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_imag_op_V_last_V_U_apdone_blk : STD_LOGIC;
    signal imag_op_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_imag_op_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_imag_op_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dft_dft_Pipeline_VITIS_LOOP_21_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        real_sample_TVALID : IN STD_LOGIC;
        imag_sample_TVALID : IN STD_LOGIC;
        real_sample_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        real_sample_TREADY : OUT STD_LOGIC;
        real_sample_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        real_sample_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        real_sample_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        imag_sample_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        imag_sample_TREADY : OUT STD_LOGIC;
        imag_sample_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        imag_sample_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        imag_sample_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        real_sample_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        real_sample_data_ce0 : OUT STD_LOGIC;
        real_sample_data_we0 : OUT STD_LOGIC;
        real_sample_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        imag_sample_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        imag_sample_data_ce0 : OUT STD_LOGIC;
        imag_sample_data_we0 : OUT STD_LOGIC;
        imag_sample_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        real_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        real_op_data_ce0 : OUT STD_LOGIC;
        real_op_data_we0 : OUT STD_LOGIC;
        real_op_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        imag_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        imag_op_data_ce0 : OUT STD_LOGIC;
        imag_op_data_we0 : OUT STD_LOGIC;
        imag_op_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dft_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        real_sample_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        real_sample_data_ce0 : OUT STD_LOGIC;
        real_sample_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        imag_sample_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        imag_sample_data_ce0 : OUT STD_LOGIC;
        imag_sample_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        real_op_data_ce0 : OUT STD_LOGIC;
        real_op_data_we0 : OUT STD_LOGIC;
        real_op_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        real_op_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        imag_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        imag_op_data_ce0 : OUT STD_LOGIC;
        imag_op_data_we0 : OUT STD_LOGIC;
        imag_op_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        imag_op_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dft_dft_Pipeline_VITIS_LOOP_67_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        real_op_TREADY : IN STD_LOGIC;
        imag_op_TREADY : IN STD_LOGIC;
        real_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        real_op_data_ce0 : OUT STD_LOGIC;
        real_op_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        imag_op_data_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        imag_op_data_ce0 : OUT STD_LOGIC;
        imag_op_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        real_op_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        real_op_TVALID : OUT STD_LOGIC;
        real_op_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_op_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        real_op_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        imag_op_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        imag_op_TVALID : OUT STD_LOGIC;
        imag_op_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        imag_op_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        imag_op_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component dft_real_sample_data_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dft_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component dft_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    real_sample_data_U : component dft_real_sample_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => real_sample_data_address0,
        ce0 => real_sample_data_ce0,
        we0 => real_sample_data_we0,
        d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_d0,
        q0 => real_sample_data_q0);

    imag_sample_data_U : component dft_real_sample_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => imag_sample_data_address0,
        ce0 => imag_sample_data_ce0,
        we0 => imag_sample_data_we0,
        d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_d0,
        q0 => imag_sample_data_q0);

    real_op_data_U : component dft_real_sample_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => real_op_data_address0,
        ce0 => real_op_data_ce0,
        we0 => real_op_data_we0,
        d0 => real_op_data_d0,
        q0 => real_op_data_q0);

    imag_op_data_U : component dft_real_sample_data_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => imag_op_data_address0,
        ce0 => imag_op_data_ce0,
        we0 => imag_op_data_we0,
        d0 => imag_op_data_d0,
        q0 => imag_op_data_q0);

    grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96 : component dft_dft_Pipeline_VITIS_LOOP_21_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start,
        ap_done => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done,
        ap_idle => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_idle,
        ap_ready => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_ready,
        real_sample_TVALID => real_sample_TVALID_int_regslice,
        imag_sample_TVALID => imag_sample_TVALID_int_regslice,
        real_sample_TDATA => real_sample_TDATA_int_regslice,
        real_sample_TREADY => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_TREADY,
        real_sample_TKEEP => real_sample_TKEEP_int_regslice,
        real_sample_TSTRB => real_sample_TSTRB_int_regslice,
        real_sample_TLAST => real_sample_TLAST_int_regslice,
        imag_sample_TDATA => imag_sample_TDATA_int_regslice,
        imag_sample_TREADY => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_TREADY,
        imag_sample_TKEEP => imag_sample_TKEEP_int_regslice,
        imag_sample_TSTRB => imag_sample_TSTRB_int_regslice,
        imag_sample_TLAST => imag_sample_TLAST_int_regslice,
        real_sample_data_address0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_address0,
        real_sample_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_ce0,
        real_sample_data_we0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_we0,
        real_sample_data_d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_d0,
        imag_sample_data_address0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_address0,
        imag_sample_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_ce0,
        imag_sample_data_we0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_we0,
        imag_sample_data_d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_d0,
        real_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_address0,
        real_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_ce0,
        real_op_data_we0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_we0,
        real_op_data_d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_d0,
        imag_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_address0,
        imag_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_ce0,
        imag_op_data_we0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_we0,
        imag_op_data_d0 => grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_d0);

    grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120 : component dft_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start,
        ap_done => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done,
        ap_idle => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_idle,
        ap_ready => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_ready,
        real_sample_data_address0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_address0,
        real_sample_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_ce0,
        real_sample_data_q0 => real_sample_data_q0,
        imag_sample_data_address0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_address0,
        imag_sample_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_ce0,
        imag_sample_data_q0 => imag_sample_data_q0,
        real_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_address0,
        real_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_ce0,
        real_op_data_we0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_we0,
        real_op_data_d0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_d0,
        real_op_data_q0 => real_op_data_q0,
        imag_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_address0,
        imag_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_ce0,
        imag_op_data_we0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_we0,
        imag_op_data_d0 => grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_d0,
        imag_op_data_q0 => imag_op_data_q0);

    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132 : component dft_dft_Pipeline_VITIS_LOOP_67_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start,
        ap_done => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done,
        ap_idle => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_idle,
        ap_ready => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_ready,
        real_op_TREADY => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TREADY,
        imag_op_TREADY => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TREADY,
        real_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_address0,
        real_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_ce0,
        real_op_data_q0 => real_op_data_q0,
        imag_op_data_address0 => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_address0,
        imag_op_data_ce0 => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_ce0,
        imag_op_data_q0 => imag_op_data_q0,
        real_op_TDATA => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TDATA,
        real_op_TVALID => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID,
        real_op_TKEEP => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TKEEP,
        real_op_TSTRB => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TSTRB,
        real_op_TLAST => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TLAST,
        imag_op_TDATA => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TDATA,
        imag_op_TVALID => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID,
        imag_op_TKEEP => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TKEEP,
        imag_op_TSTRB => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TSTRB,
        imag_op_TLAST => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TLAST);

    control_s_axi_U : component dft_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_real_sample_V_data_V_U : component dft_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_sample_TDATA,
        vld_in => real_sample_TVALID,
        ack_in => regslice_both_real_sample_V_data_V_U_ack_in,
        data_out => real_sample_TDATA_int_regslice,
        vld_out => real_sample_TVALID_int_regslice,
        ack_out => real_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_real_sample_V_data_V_U_apdone_blk);

    regslice_both_real_sample_V_keep_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_sample_TKEEP,
        vld_in => real_sample_TVALID,
        ack_in => regslice_both_real_sample_V_keep_V_U_ack_in,
        data_out => real_sample_TKEEP_int_regslice,
        vld_out => regslice_both_real_sample_V_keep_V_U_vld_out,
        ack_out => real_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_real_sample_V_keep_V_U_apdone_blk);

    regslice_both_real_sample_V_strb_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_sample_TSTRB,
        vld_in => real_sample_TVALID,
        ack_in => regslice_both_real_sample_V_strb_V_U_ack_in,
        data_out => real_sample_TSTRB_int_regslice,
        vld_out => regslice_both_real_sample_V_strb_V_U_vld_out,
        ack_out => real_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_real_sample_V_strb_V_U_apdone_blk);

    regslice_both_real_sample_V_last_V_U : component dft_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_sample_TLAST,
        vld_in => real_sample_TVALID,
        ack_in => regslice_both_real_sample_V_last_V_U_ack_in,
        data_out => real_sample_TLAST_int_regslice,
        vld_out => regslice_both_real_sample_V_last_V_U_vld_out,
        ack_out => real_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_real_sample_V_last_V_U_apdone_blk);

    regslice_both_imag_sample_V_data_V_U : component dft_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_sample_TDATA,
        vld_in => imag_sample_TVALID,
        ack_in => regslice_both_imag_sample_V_data_V_U_ack_in,
        data_out => imag_sample_TDATA_int_regslice,
        vld_out => imag_sample_TVALID_int_regslice,
        ack_out => imag_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_sample_V_data_V_U_apdone_blk);

    regslice_both_imag_sample_V_keep_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_sample_TKEEP,
        vld_in => imag_sample_TVALID,
        ack_in => regslice_both_imag_sample_V_keep_V_U_ack_in,
        data_out => imag_sample_TKEEP_int_regslice,
        vld_out => regslice_both_imag_sample_V_keep_V_U_vld_out,
        ack_out => imag_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_sample_V_keep_V_U_apdone_blk);

    regslice_both_imag_sample_V_strb_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_sample_TSTRB,
        vld_in => imag_sample_TVALID,
        ack_in => regslice_both_imag_sample_V_strb_V_U_ack_in,
        data_out => imag_sample_TSTRB_int_regslice,
        vld_out => regslice_both_imag_sample_V_strb_V_U_vld_out,
        ack_out => imag_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_sample_V_strb_V_U_apdone_blk);

    regslice_both_imag_sample_V_last_V_U : component dft_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_sample_TLAST,
        vld_in => imag_sample_TVALID,
        ack_in => regslice_both_imag_sample_V_last_V_U_ack_in,
        data_out => imag_sample_TLAST_int_regslice,
        vld_out => regslice_both_imag_sample_V_last_V_U_vld_out,
        ack_out => imag_sample_TREADY_int_regslice,
        apdone_blk => regslice_both_imag_sample_V_last_V_U_apdone_blk);

    regslice_both_real_op_V_data_V_U : component dft_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_op_TDATA_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID,
        ack_in => real_op_TREADY_int_regslice,
        data_out => real_op_TDATA,
        vld_out => regslice_both_real_op_V_data_V_U_vld_out,
        ack_out => real_op_TREADY,
        apdone_blk => regslice_both_real_op_V_data_V_U_apdone_blk);

    regslice_both_real_op_V_keep_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_op_TKEEP_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID,
        ack_in => regslice_both_real_op_V_keep_V_U_ack_in_dummy,
        data_out => real_op_TKEEP,
        vld_out => regslice_both_real_op_V_keep_V_U_vld_out,
        ack_out => real_op_TREADY,
        apdone_blk => regslice_both_real_op_V_keep_V_U_apdone_blk);

    regslice_both_real_op_V_strb_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_op_TSTRB_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID,
        ack_in => regslice_both_real_op_V_strb_V_U_ack_in_dummy,
        data_out => real_op_TSTRB,
        vld_out => regslice_both_real_op_V_strb_V_U_vld_out,
        ack_out => real_op_TREADY,
        apdone_blk => regslice_both_real_op_V_strb_V_U_apdone_blk);

    regslice_both_real_op_V_last_V_U : component dft_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => real_op_TLAST_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID,
        ack_in => regslice_both_real_op_V_last_V_U_ack_in_dummy,
        data_out => real_op_TLAST,
        vld_out => regslice_both_real_op_V_last_V_U_vld_out,
        ack_out => real_op_TREADY,
        apdone_blk => regslice_both_real_op_V_last_V_U_apdone_blk);

    regslice_both_imag_op_V_data_V_U : component dft_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_op_TDATA_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID,
        ack_in => imag_op_TREADY_int_regslice,
        data_out => imag_op_TDATA,
        vld_out => regslice_both_imag_op_V_data_V_U_vld_out,
        ack_out => imag_op_TREADY,
        apdone_blk => regslice_both_imag_op_V_data_V_U_apdone_blk);

    regslice_both_imag_op_V_keep_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_op_TKEEP_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID,
        ack_in => regslice_both_imag_op_V_keep_V_U_ack_in_dummy,
        data_out => imag_op_TKEEP,
        vld_out => regslice_both_imag_op_V_keep_V_U_vld_out,
        ack_out => imag_op_TREADY,
        apdone_blk => regslice_both_imag_op_V_keep_V_U_apdone_blk);

    regslice_both_imag_op_V_strb_V_U : component dft_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_op_TSTRB_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID,
        ack_in => regslice_both_imag_op_V_strb_V_U_ack_in_dummy,
        data_out => imag_op_TSTRB,
        vld_out => regslice_both_imag_op_V_strb_V_U_vld_out,
        ack_out => imag_op_TREADY,
        apdone_blk => regslice_both_imag_op_V_strb_V_U_apdone_blk);

    regslice_both_imag_op_V_last_V_U : component dft_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => imag_op_TLAST_int_regslice,
        vld_in => grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID,
        ack_in => regslice_both_imag_op_V_last_V_U_ack_in_dummy,
        data_out => imag_op_TLAST,
        vld_out => regslice_both_imag_op_V_last_V_U_vld_out,
        ack_out => imag_op_TREADY,
        apdone_blk => regslice_both_imag_op_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_ready = ap_const_logic_1)) then 
                    grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID = ap_const_logic_1))) then
                imag_op_TDATA_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TDATA;
                imag_op_TKEEP_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TKEEP;
                imag_op_TLAST_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TLAST;
                imag_op_TSTRB_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID = ap_const_logic_1))) then
                real_op_TDATA_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TDATA;
                real_op_TKEEP_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TKEEP;
                real_op_TLAST_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TLAST;
                real_op_TSTRB_reg <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_block_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done)
    begin
        if ((grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done)
    begin
        if ((grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done)
    begin
        if ((grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8)
    begin
        if ((ap_const_boolean_1 = ap_block_state8)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state8_assign_proc : process(regslice_both_real_op_V_data_V_U_apdone_blk, regslice_both_imag_op_V_data_V_U_apdone_blk)
    begin
                ap_block_state8 <= ((regslice_both_imag_op_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_real_op_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state8, ap_block_state8)
    begin
        if (((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, ap_block_state8)
    begin
        if (((ap_const_boolean_0 = ap_block_state8) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_ap_start_reg;
    grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_ap_start_reg;
    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_ap_start_reg;
    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TREADY <= (imag_op_TREADY_int_regslice and ap_CS_fsm_state7);
    grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TREADY <= (real_op_TREADY_int_regslice and ap_CS_fsm_state7);

    imag_op_TDATA_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TDATA, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID, ap_CS_fsm_state7, imag_op_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID = ap_const_logic_1))) then 
            imag_op_TDATA_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TDATA;
        else 
            imag_op_TDATA_int_regslice <= imag_op_TDATA_reg;
        end if; 
    end process;


    imag_op_TKEEP_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TKEEP, ap_CS_fsm_state7, imag_op_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID = ap_const_logic_1))) then 
            imag_op_TKEEP_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TKEEP;
        else 
            imag_op_TKEEP_int_regslice <= imag_op_TKEEP_reg;
        end if; 
    end process;


    imag_op_TLAST_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TLAST, ap_CS_fsm_state7, imag_op_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID = ap_const_logic_1))) then 
            imag_op_TLAST_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TLAST;
        else 
            imag_op_TLAST_int_regslice <= imag_op_TLAST_reg;
        end if; 
    end process;


    imag_op_TSTRB_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TSTRB, ap_CS_fsm_state7, imag_op_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID = ap_const_logic_1))) then 
            imag_op_TSTRB_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TSTRB;
        else 
            imag_op_TSTRB_int_regslice <= imag_op_TSTRB_reg;
        end if; 
    end process;

    imag_op_TVALID <= regslice_both_imag_op_V_data_V_U_vld_out;
    imag_op_TVALID_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_TVALID;

    imag_op_data_address0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_address0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_address0, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_address0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            imag_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_address0;
        else 
            imag_op_data_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    imag_op_data_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_ce0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_ce0, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            imag_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_imag_op_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_ce0;
        else 
            imag_op_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    imag_op_data_d0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_d0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_op_data_d0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_op_data_d0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_d0;
        else 
            imag_op_data_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    imag_op_data_we0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_we0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_op_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_op_data_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_op_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_op_data_we0;
        else 
            imag_op_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    imag_sample_TREADY <= regslice_both_imag_sample_V_data_V_U_ack_in;

    imag_sample_TREADY_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_sample_TREADY_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_TREADY;
        else 
            imag_sample_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    imag_sample_data_address0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_address0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_sample_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_sample_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_address0;
        else 
            imag_sample_data_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    imag_sample_data_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_ce0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imag_sample_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_imag_sample_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_sample_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_ce0;
        else 
            imag_sample_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    imag_sample_data_we0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            imag_sample_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_imag_sample_data_we0;
        else 
            imag_sample_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    real_op_TDATA_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TDATA, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID, ap_CS_fsm_state7, real_op_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID = ap_const_logic_1))) then 
            real_op_TDATA_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TDATA;
        else 
            real_op_TDATA_int_regslice <= real_op_TDATA_reg;
        end if; 
    end process;


    real_op_TKEEP_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TKEEP, ap_CS_fsm_state7, real_op_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID = ap_const_logic_1))) then 
            real_op_TKEEP_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TKEEP;
        else 
            real_op_TKEEP_int_regslice <= real_op_TKEEP_reg;
        end if; 
    end process;


    real_op_TLAST_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TLAST, ap_CS_fsm_state7, real_op_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID = ap_const_logic_1))) then 
            real_op_TLAST_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TLAST;
        else 
            real_op_TLAST_int_regslice <= real_op_TLAST_reg;
        end if; 
    end process;


    real_op_TSTRB_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TSTRB, ap_CS_fsm_state7, real_op_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID = ap_const_logic_1))) then 
            real_op_TSTRB_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TSTRB;
        else 
            real_op_TSTRB_int_regslice <= real_op_TSTRB_reg;
        end if; 
    end process;

    real_op_TVALID <= regslice_both_real_op_V_data_V_U_vld_out;
    real_op_TVALID_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_TVALID;

    real_op_data_address0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_address0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_address0, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_address0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            real_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_op_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_address0;
        else 
            real_op_data_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    real_op_data_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_ce0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_ce0, grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            real_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_67_4_fu_132_real_op_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_op_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_ce0;
        else 
            real_op_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    real_op_data_d0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_d0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_op_data_d0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_op_data_d0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_d0;
        else 
            real_op_data_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    real_op_data_we0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_we0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_op_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_op_data_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_op_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_op_data_we0;
        else 
            real_op_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    real_sample_TREADY <= regslice_both_real_sample_V_data_V_U_ack_in;

    real_sample_TREADY_int_regslice_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_sample_TREADY_int_regslice <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_TREADY;
        else 
            real_sample_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    real_sample_data_address0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_address0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_sample_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_sample_data_address0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_address0;
        else 
            real_sample_data_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    real_sample_data_ce0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_ce0, grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            real_sample_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_43_2_VITIS_LOOP_44_3_fu_120_real_sample_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_sample_data_ce0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_ce0;
        else 
            real_sample_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    real_sample_data_we0_assign_proc : process(grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            real_sample_data_we0 <= grp_dft_Pipeline_VITIS_LOOP_21_1_fu_96_real_sample_data_we0;
        else 
            real_sample_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
