# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.srcs/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0.xci
# IP: The module: 'design_dft_keep_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.srcs/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0.xci
# IP: The module: 'design_dft_keep_axi_dma_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_dma_1_0/design_dft_keep_axi_dma_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_dma_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
