# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.srcs/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/design_dft_keep_axi_smc_0.xci
# IP: The module: 'design_dft_keep_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/bd_f785.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_0/bd_f785_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_2/bd_f785_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_3/bd_f785_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_4/bd_f785_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_5/bd_f785_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_6/bd_f785_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_7/bd_f785_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_8/bd_f785_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_9/bd_f785_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_10/bd_f785_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_11/bd_f785_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_12/bd_f785_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_13/bd_f785_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_14/bd_f785_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_15/bd_f785_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_16/bd_f785_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_17/bd_f785_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_18/bd_f785_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_19/bd_f785_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_20/bd_f785_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_21/bd_f785_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_22/bd_f785_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_23/bd_f785_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_24/bd_f785_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_25/bd_f785_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_26/bd_f785_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_27/bd_f785_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_28/bd_f785_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_29/bd_f785_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_30/bd_f785_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_31/bd_f785_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_32/bd_f785_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_33/bd_f785_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_34/bd_f785_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_35/bd_f785_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_36/bd_f785_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_37/bd_f785_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_38/bd_f785_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_39/bd_f785_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_40/bd_f785_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_41/bd_f785_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_42/bd_f785_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_43/bd_f785_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_44/bd_f785_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_45/bd_f785_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_46/bd_f785_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_2/bd_f785_arinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_3/bd_f785_rinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_4/bd_f785_awinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_5/bd_f785_winsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_6/bd_f785_binsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_7/bd_f785_aroutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_8/bd_f785_routsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_9/bd_f785_awoutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_10/bd_f785_woutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_11/bd_f785_boutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_12/bd_f785_arni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_13/bd_f785_rni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_14/bd_f785_awni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_15/bd_f785_wni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_16/bd_f785_bni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_20/bd_f785_s00a2s_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_21/bd_f785_sarn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_22/bd_f785_srn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_23/bd_f785_sawn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_24/bd_f785_swn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_25/bd_f785_sbn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_26/bd_f785_m00s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_27/bd_f785_m00arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_28/bd_f785_m00rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_29/bd_f785_m00awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_30/bd_f785_m00wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_31/bd_f785_m00bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_33/bd_f785_m01s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_34/bd_f785_m01arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_35/bd_f785_m01rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_36/bd_f785_m01awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_37/bd_f785_m01wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_38/bd_f785_m01bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_40/bd_f785_m02s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_41/bd_f785_m02arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_42/bd_f785_m02rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_43/bd_f785_m02awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_44/bd_f785_m02wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_45/bd_f785_m02bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.srcs/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/design_dft_keep_axi_smc_0.xci
# IP: The module: 'design_dft_keep_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/bd_f785.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_0/bd_f785_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_2/bd_f785_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_3/bd_f785_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_4/bd_f785_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_5/bd_f785_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_6/bd_f785_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_7/bd_f785_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_8/bd_f785_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_9/bd_f785_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_10/bd_f785_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_11/bd_f785_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_12/bd_f785_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_13/bd_f785_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_14/bd_f785_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_15/bd_f785_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_16/bd_f785_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_17/bd_f785_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_18/bd_f785_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_19/bd_f785_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_20/bd_f785_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_21/bd_f785_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_22/bd_f785_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_23/bd_f785_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_24/bd_f785_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_25/bd_f785_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_26/bd_f785_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_27/bd_f785_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_28/bd_f785_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_29/bd_f785_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_30/bd_f785_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_31/bd_f785_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_32/bd_f785_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_33/bd_f785_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_34/bd_f785_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_35/bd_f785_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_36/bd_f785_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_37/bd_f785_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_38/bd_f785_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_39/bd_f785_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_40/bd_f785_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_41/bd_f785_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_42/bd_f785_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_43/bd_f785_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_44/bd_f785_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_45/bd_f785_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_46/bd_f785_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_1/bd_f785_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_2/bd_f785_arinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_3/bd_f785_rinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_4/bd_f785_awinsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_5/bd_f785_winsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_6/bd_f785_binsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_7/bd_f785_aroutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_8/bd_f785_routsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_9/bd_f785_awoutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_10/bd_f785_woutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_11/bd_f785_boutsw_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_12/bd_f785_arni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_13/bd_f785_rni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_14/bd_f785_awni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_15/bd_f785_wni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_16/bd_f785_bni_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_20/bd_f785_s00a2s_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_21/bd_f785_sarn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_22/bd_f785_srn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_23/bd_f785_sawn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_24/bd_f785_swn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_25/bd_f785_sbn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_26/bd_f785_m00s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_27/bd_f785_m00arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_28/bd_f785_m00rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_29/bd_f785_m00awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_30/bd_f785_m00wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_31/bd_f785_m00bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_33/bd_f785_m01s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_34/bd_f785_m01arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_35/bd_f785_m01rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_36/bd_f785_m01awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_37/bd_f785_m01wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_38/bd_f785_m01bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_40/bd_f785_m02s2a_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_41/bd_f785_m02arn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_42/bd_f785_m02rn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_43/bd_f785_m02awn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_44/bd_f785_m02wn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/bd_0/ip/ip_45/bd_f785_m02bn_0_ooc.xdc

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/linux/ieng6/students/186/dnwadhwani/Desktop/project3/Read_the_docs/project_files/project3/dft_1024_precomputed/project_dft__keep/project_dft__keep.gen/sources_1/bd/design_dft_keep/ip/design_dft_keep_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dft_keep_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
